n=input('digite uma variável:')
print('essa variável "{}" tem tipo {}'.format(n,type(n)))
print('É alfabética? ',(n.isalpha()))
print('É numérica? ',(n.isnumeric()))
print('É alfanumérico? ',(n.isalnum()))
print('É decimal? ',(n.isdecimal()))
print('É minuscula? ',(n.islower()))
print('É maiuscula? ',(n.isupper()))
print('É apenas espaços? ',(n.isspace()))
print('É capitalizada? ',(n.istitle()))
